AllCops:
  Exclude:
    - 'spec/examples.txt'
    - '/spec/fixtures/**/*'
    - 'saxerator.gemspec'
  DisplayCopNames: true
  TargetRubyVersion: 2.0

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/NumericLiterals:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/SymbolProc:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/IndentArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/StringLiterals:
  Enabled: false